datasets:
  test:
    path: eval/test/
    fx: 718.856
    fy: 718.856
    cx: 607.2
    cy: 185.2
    w: 1241
    h: 376
  test2:
    path: eval/test1.mp4
    fx: 718.856
    fy: 718.856
    cx: 607.2
    cy: 185.2
    w: 1241
    h: 376
  test3:
    path: eval/test2.mp4
    fx: 718.856
    fy: 718.856
    cx: 607.2
    cy: 185.2
    w: 1241
    h: 376
  webcam:
    path: 0
    fx: 718.856
    fy: 718.856
    cx: 320
    cy: 240
    w: 640
    h: 480
